name: 'Build Frontend'
on:
  push:
    branches:
      - 'master'
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Login to Registry
        run: docker login $REGISTRY -u $USER -p $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: docker.pkg.github.com
          USER: arpadgabor

      - name: Build image
        run: docker build . -t "$REGISTRY/$IMAGE:$GITHUB_SHA" --file $FOLDER_PATH/Dockerfile
        env:
          FOLDER_PATH: web
          REGISTRY: docker.pkg.github.com
          IMAGE: arpadgabor/educatiepentrutoti/web
          
      - name: Show images
        run: docker images

      - name: Push to Registry
        run: docker push "$REGISTRY/$IMAGE:$GITHUB_SHA"
        env:
          REGISTRY: docker.pkg.github.com
          IMAGE: arpadgabor/educatiepentrutoti/web
