name: 'Build Frontend'
on:
  push:
    branches:
      - 'master'
    paths:
      - 'web/**'
      - '.github/workflows/build-web.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Login to Registry
        run: docker login $REGISTRY -u $USER -p $TOKEN
        env:
          USER: arpadgabor
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: docker.pkg.github.com

      - name: Build image
        run: docker build $BUILD_ARGS . -t "$REGISTRY/$GITHUB_REPOSITORY/$TAG:$GITHUB_SHA" --file $FOLDER_PATH/Dockerfile
        env:
          TAG: web
          FOLDER_PATH: web
          REGISTRY: docker.pkg.github.com
          BUILD_ARGS: --build-arg API_URL=${{ secrets.API_URL }} --build-arg ONESIGNAL_ID=${{ secrets.ONESIGNAL_ID }}

      - name: Push to Registry
        run: docker push "$REGISTRY/$GITHUB_REPOSITORY/$TAG:$GITHUB_SHA"
        env:
          TAG: web
          REGISTRY: docker.pkg.github.com
